### PR TITLE
Add pre-destroy method to PeerServer

### PR DESCRIPTION
**Pull request by rktoomey**
And any other additional resource closing fixes

### CODE REVIEW

**Comment by ewiner** [comment]
👍 

But I'm not quite sure the best way to integrate it.  @dwhjames can you help?

**Comment by dwhjames** [comment]
> But I'm not quite sure the best way to integrate it.

I don’t follow

**Comment by ewiner** [comment]
For these PRs on top of `gemini-release-dmz`, what's the procedure?  Just merge it then merge that to `gemini-release`?  Or do you want to do more things to preserve the upstream-PR-ability of this change?

**Comment by dwhjames** [comment]
Ah,
yes, for PRs that ended up branching from `gemini-release-dmz`, we’re just going to have to wait until the queue of PRs upstream have been merged, such that `develop` effectively catches up with `gemini-release-dmz`.

Maybe it’s possible to backport this PR now, but hopefully there’ll be some movement in that queue soon.

**Comment by dwhjames** [comment]
Anyway, I’ll run the test suite myself, to avoid a repeat of yesterday, and then merge and publish a new build.

**Pull request merged**
